### ISSUE TITLE
1) Crear repositorio en github -admin

### ISSUE THREAD

**Issue by GitHub-Adel** [GitHub-Adel/git-github#1]
es almacenamiento en la nube para tener nuestro proyecto protegido y poder
descargarlo desde cualquier lugar, esto nos permite trabajar con colaboradores de
otro lugar incluso pais.

1) iniciar sesion en github.
1) ir al signo + al lado del usaurio
2) click derecho y new repository
3) llenar los datos
4) Initialize this repository with a README
5) create reposotory

fin

**Comment by desarrollador-prueba** [comment]
completada
